### ISSUE TITLE
[CLI] sync - Delete files that are no longer managed by coat

### ISSUE THREAD

**Issue by peterjuras** [coat-dev/coat#31]
## Summary

Files which are declared by a coat manifest and are created by running `coat sync` in a project are currently not being deleted after the coat manifest or its underlying template are updated or removed. This makes it cumbersome to switch from one template to another, e.g. changing build tooling (switching from webpack to rollup) without leaving artifacts and unused files behind.

Since the files that are generated by `coat sync` are deterministic, files that have been generated in the previous sync but are no longer generated in the current sync should be deleted. There should be no warning or message for now, since the project has to be within a .git repository and deletions should be tracked by git (or not checked in yet, which could still be a valid scenario which does not warrant a warning on deletion, e.g. when trying out different coat templates before choosing one and checking it in).

## Implementation plan

In order to know which files have been generated by the previous `coat sync` execution, the generated files should be persisted in a lockfile:

- Name: `coat.lock`
- Location: stored next to the coat manifest file `coat.json`

### Lockfile schema:
The lockfile should be generated in YAML, to make diffs more human readable. All properties should be sorted alphabetically, to make the output deterministic.

```yaml
version: 1 # coat lockfile version
files: # alphabetically sorted
  # File entries are objects to allow additions to the lockfile schema, e.g. the checksum
  # to track the file contents and warn before deletion.
  - path: path/to/file # relative path to file from the coat manifest location
```
